### ISSUE TITLE
No videofeed 

### ISSUE THREAD

**Issue by phoneix1221** [GraphtyLove/Face-recognition-project#20]
There is no footage in web browser from my laptop camera.  im using windows

**Comment by GraphtyLove** [comment]
Yes this is normal, because I defined the video feed to a camera that is not online anymore. you have to change the value of the src attribute in the video tag.
[In this file.](https://github.com/GraphtyLove/Face-recognition-project/blob/master/FRONT/late-checker/src/Components/VideoFeed/VideoFeed.jsx)

**Comment by rsingh2083** [comment]
> There is no footage in web browser from my laptop camera. im using windows

Hi, 
were you able to run this ? I need some help ! Have raised two queries, can you look at them.
Or maybe upload your working repository
